[package]
authors = ["tamasfe"]
edition = "2018"
name = "pretty-lint"
version = "0.1.1"
description = "A very simple library for showing lint errors"
license = "MIT"
repository = "https://github.com/tamasfe/pretty-lint"

[dependencies]
colored = { version = "2", path = "../colored" }
